name: CI

on: [ push, pull_request ]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         -
            uses: actions/checkout@v3
            with:
               fetch-depth: 0 # Fetch all history
         -
            uses: actions/setup-node@v3
            with:
               node-version-file: '.nvmrc'
         - run: npm i -g npm@8.5.5
         - run: npm ci
         - run: npm run build
         -
            uses: actions/upload-artifact@v3
            with:
               name: minified
               path: .minified/index.zip
         - run: unzip .minified/index.zip -d .gh-pages
         -
            uses: actions/upload-pages-artifact@v1
            with:
               path: '.gh-pages'
         -
            uses: actions/checkout@v3
            with:
               ref: ipfs
               path: ipfs
         -
            run: |
               cp .minified/index.html ipfs/
               cd ipfs
               git config --global user.name "${GITHUB_ACTOR}"
               git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
               git commit -am "build: update ipfs"
               git push
   deploy:
      if: github.ref == 'refs/heads/master'
      needs: [ build ]
      runs-on: ubuntu-latest
      permissions:
         pages: write
         id-token: write
      steps:
         - uses: actions/deploy-pages@v2
         -
            uses: actions/download-artifact@v3
            with:
               name: minified
