name: CI

on: [ push, pull_request ]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         -
            uses: actions/checkout@v3
            with:
               fetch-depth: 0 # Fetch all history
         -
            uses: actions/setup-node@v3
            with:
               node-version-file: '.nvmrc'
         - run: npm i -g npm@8.5.5
         - run: npm ci
         - run: npm run build
         -
            uses: actions/upload-artifact@v3
            with:
               name: minified
               path: .minified/index.zip
         - run: unzip .minified/index.zip -d .gh-pages
         -
            uses: actions/upload-pages-artifact@v1
            with:
               path: '.gh-pages'
   deploy:
      if: github.ref == 'refs/heads/master'
      needs: [ build ]
      runs-on: ubuntu-latest
      permissions:
         pages: write
         id-token: write
      steps:
         - uses: actions/deploy-pages@v2
         -
            uses: actions/download-artifact@v3
            with:
               name: minified
         - run: unzip index.zip
         - run: ls -R
         -
            uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
            with:
               pin-name: js13k23-portolani
               path: index.html
               remove-old: true
               verbose: false
               pinata-api-key: ${{ secrets.PINATA_API_KEY }}
               pinata-secret-api-key: ${{ secrets.PINATA_SECRET_API_KEY }}
